name: Build container image
on:
  push:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository }}
  GITHUB_SHA_SHORT: '' # filled by rlespinasse/github-slug-action@v5
  GITHUB_REF_POINT_SLUG_URL: '' # filled by rlespinasse/github-slug-action@v5
  GITHUB_REPOSITORY_NAME_PART_SLUG_URL: '' # filled by rlespinasse/github-slug-action@v5
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: lowercase IMAGE_REGISTRY
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY@L}" >> "${GITHUB_ENV}"
      - name: Inject enhanced GitHub environment variables
        uses: rlespinasse/github-slug-action@v5 # https://github.com/rlespinasse/github-slug-action
      - name: Clear space
        run: |
          df -h /
          sudo rm -rf \
          "$AGENT_TOOLSDIRECTORY" \
          /opt/google/chrome \
          /opt/microsoft/msedge \
          /opt/microsoft/powershell \
          /opt/pipx \
          /usr/lib/mono \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/lib/node_modules \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift
          df -h /
      # Build image using Buildah action https://github.com/redhat-actions/buildah-build
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}
          tags: ${{ env.GITHUB_REF_POINT_SLUG_URL }} ${{ env.GITHUB_SHA_SHORT }}
          containerfiles: |
            ./Dockerfile
          oci: true
          layers: true
      # Push the image to GHCR (Image Registry) https://github.com/redhat-actions/push-to-registry
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"